### ISSUE TITLE
purchase_rfq_number

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/purchase-workflow#1]
Konsepnya sama seperti modul sale_quotation_number pada OCA/sale-workflow

CC: @azmimr67 @mikevhe18

**Comment by mikevhe18** [comment]
PR TO OCA [#223](https://github.com/OCA/purchase-workflow/pull/223)

**Comment by mikevhe18** [comment]
@andhit-r mas, gue gak bisa ganti labelnyaa ke pr-to-oca
