### ISSUE TITLE
purchase_requisition_type

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/purchase-workflow#2]
dependensi:
- purchase_order_type (https://github.com/OCA/purchase-workflow/tree/8.0/purchase_order_type)

TODO:
- [ ] Menambahkan field **order_type** pada purchase.requisition. Penambahan field persis seperti https://github.com/OCA/purchase-workflow/blob/8.0/purchase_order_type/models/purchase_order.py
- [ ] Menambahkan field **order_type** pada form purchase.requisition di bawah field **user_id**
- [ ] Membuat override terhadap method **_prepare_purchase_order** milik purchase.requisition. Buat sehingga purchase.order yang dihasilkan mempunyai nilai order_type yang sama dengan purchase.requisition

Analytic account:
1. purchase_requisition_type - Natura Aromatik (100%)

**Comment by andhit-r** [comment]
@mikevhe18 ini dikerjain yah. Tengkyu.

**Comment by mikevhe18** [comment]
PR TO OCA [#231](https://github.com/OCA/purchase-workflow/pull/231)

**Comment by mikevhe18** [comment]
@andhit-r Mas, PR ini udah dimerged. Gue gak bisa closed
